// auto-generated by script tools/embed_resource.py
// DO NOT EDIT BY HAND

#ifndef ESP8266Clock_resource_data_H_
#define ESP8266Clock_resource_data_H_

#include <Arduino.h>

namespace Resource {
extern const char   _common_css[] PROGMEM;
extern const size_t len_common_css;
extern const char   etag_common_css[] PROGMEM;
extern const char   _index_html[] PROGMEM;
extern const size_t len_index_html;
extern const char   etag_index_html[] PROGMEM;
extern const char   _index_js[] PROGMEM;
extern const size_t len_index_js;
extern const char   etag_index_js[] PROGMEM;
extern const char   _TZ_js[] PROGMEM;
extern const size_t len_TZ_js;
extern const char   etag_TZ_js[] PROGMEM;
extern const char   _wait_reboot_html[] PROGMEM;
extern const size_t len_wait_reboot_html;
extern const char   etag_wait_reboot_html[] PROGMEM;

} // namespace Resource

#endif // ESP8266Clock_resource_data_H_
