// auto-generated by script tools/TZupdate.py
// DO NOT EDIT BY HAND
//
// This database is autogenerated from IANA timezone database
//      https://www.iana.org/time-zones
// via: https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv

#include "TZDB.h"

PGM_P TZDB::getTZ(const String &area, const String &city) {
  const char *a = area.c_str();
  const char *c = city.c_str();
  int r;
  if (strcmp_P(a, PSTR("Africa")) == 0) {
    r = strcmp_P(c, PSTR("Juba"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Cairo"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Bamako"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Addis_Ababa"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Abidjan")) == 0) return TZ_Africa_Abidjan;
            else if (strcmp_P(c, PSTR("Accra")) == 0) return TZ_Africa_Accra;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Algiers")) == 0) return TZ_Africa_Algiers;
            else if (strcmp_P(c, PSTR("Asmara")) == 0) return TZ_Africa_Asmara;
            else return nullptr;
          } else {
            return TZ_Africa_Addis_Ababa;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Bissau"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Bangui")) == 0) return TZ_Africa_Bangui;
            else if (strcmp_P(c, PSTR("Banjul")) == 0) return TZ_Africa_Banjul;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Brazzaville"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Blantyre")) == 0) return TZ_Africa_Blantyre;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Bujumbura")) == 0) return TZ_Africa_Bujumbura;
              else return nullptr;
            } else {
              return TZ_Africa_Brazzaville;
            }
          } else {
            return TZ_Africa_Bissau;
          }
        } else {
          return TZ_Africa_Bamako;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Djibouti"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Conakry"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Casablanca")) == 0) return TZ_Africa_Casablanca;
            else if (strcmp_P(c, PSTR("Ceuta")) == 0) return TZ_Africa_Ceuta;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Dakar")) == 0) return TZ_Africa_Dakar;
            else if (strcmp_P(c, PSTR("Dar_es_Salaam")) == 0) return TZ_Africa_Dar_es_Salaam;
            else return nullptr;
          } else {
            return TZ_Africa_Conakry;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Freetown"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Douala")) == 0) return TZ_Africa_Douala;
            else if (strcmp_P(c, PSTR("El_Aaiun")) == 0) return TZ_Africa_El_Aaiun;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Harare"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Gaborone")) == 0) return TZ_Africa_Gaborone;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Johannesburg")) == 0) return TZ_Africa_Johannesburg;
              else return nullptr;
            } else {
              return TZ_Africa_Harare;
            }
          } else {
            return TZ_Africa_Freetown;
          }
        } else {
          return TZ_Africa_Djibouti;
        }
      } else {
        return TZ_Africa_Cairo;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Maseru"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Libreville"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Kigali"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Kampala")) == 0) return TZ_Africa_Kampala;
            else if (strcmp_P(c, PSTR("Khartoum")) == 0) return TZ_Africa_Khartoum;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Kinshasa")) == 0) return TZ_Africa_Kinshasa;
            else if (strcmp_P(c, PSTR("Lagos")) == 0) return TZ_Africa_Lagos;
            else return nullptr;
          } else {
            return TZ_Africa_Kigali;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Lubumbashi"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Lome")) == 0) return TZ_Africa_Lome;
            else if (strcmp_P(c, PSTR("Luanda")) == 0) return TZ_Africa_Luanda;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Malabo"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Lusaka")) == 0) return TZ_Africa_Lusaka;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Maputo")) == 0) return TZ_Africa_Maputo;
              else return nullptr;
            } else {
              return TZ_Africa_Malabo;
            }
          } else {
            return TZ_Africa_Lubumbashi;
          }
        } else {
          return TZ_Africa_Libreville;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Nouakchott"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Monrovia"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Mbabane")) == 0) return TZ_Africa_Mbabane;
            else if (strcmp_P(c, PSTR("Mogadishu")) == 0) return TZ_Africa_Mogadishu;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Ndjamena"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Nairobi")) == 0) return TZ_Africa_Nairobi;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Niamey")) == 0) return TZ_Africa_Niamey;
              else return nullptr;
            } else {
              return TZ_Africa_Ndjamena;
            }
          } else {
            return TZ_Africa_Monrovia;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Sao_Tome"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Ouagadougou")) == 0) return TZ_Africa_Ouagadougou;
            else if (strcmp_P(c, PSTR("Porto-Novo")) == 0) return TZ_Africa_PortomNovo;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Tunis"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Tripoli")) == 0) return TZ_Africa_Tripoli;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Windhoek")) == 0) return TZ_Africa_Windhoek;
              else return nullptr;
            } else {
              return TZ_Africa_Tunis;
            }
          } else {
            return TZ_Africa_Sao_Tome;
          }
        } else {
          return TZ_Africa_Nouakchott;
        }
      } else {
        return TZ_Africa_Maseru;
      }
    } else {
      return TZ_Africa_Juba;
    }
  }
  else if (strcmp_P(a, PSTR("America")) == 0) {
    r = strcmp_P(c, PSTR("Iqaluit"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Chihuahua"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Aruba"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Argentina/Jujuy"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Antigua"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Anchorage"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Adak")) == 0) return TZ_America_Adak;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Anguilla")) == 0) return TZ_America_Anguilla;
                else return nullptr;
              } else {
                return TZ_America_Anchorage;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Argentina/Buenos_Aires"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Araguaina")) == 0) return TZ_America_Araguaina;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Argentina/Catamarca")) == 0) return TZ_America_Argentina_Catamarca;
                else if (strcmp_P(c, PSTR("Argentina/Cordoba")) == 0) return TZ_America_Argentina_Cordoba;
                else return nullptr;
              } else {
                return TZ_America_Argentina_Buenos_Aires;
              }
            } else {
              return TZ_America_Antigua;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Argentina/Salta"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Argentina/Mendoza"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Argentina/La_Rioja")) == 0) return TZ_America_Argentina_La_Rioja;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Argentina/Rio_Gallegos")) == 0) return TZ_America_Argentina_Rio_Gallegos;
                else return nullptr;
              } else {
                return TZ_America_Argentina_Mendoza;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Argentina/San_Luis"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Argentina/San_Juan")) == 0) return TZ_America_Argentina_San_Juan;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Argentina/Tucuman")) == 0) return TZ_America_Argentina_Tucuman;
                else if (strcmp_P(c, PSTR("Argentina/Ushuaia")) == 0) return TZ_America_Argentina_Ushuaia;
                else return nullptr;
              } else {
                return TZ_America_Argentina_San_Luis;
              }
            } else {
              return TZ_America_Argentina_Salta;
            }
          } else {
            return TZ_America_Argentina_Jujuy;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Boa_Vista"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Bahia_Banderas"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Atikokan"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Asuncion")) == 0) return TZ_America_Asuncion;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Bahia")) == 0) return TZ_America_Bahia;
                else return nullptr;
              } else {
                return TZ_America_Atikokan;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Belem"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Barbados")) == 0) return TZ_America_Barbados;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Belize")) == 0) return TZ_America_Belize;
                else if (strcmp_P(c, PSTR("Blanc-Sablon")) == 0) return TZ_America_BlancmSablon;
                else return nullptr;
              } else {
                return TZ_America_Belem;
              }
            } else {
              return TZ_America_Bahia_Banderas;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Cancun"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Boise"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Bogota")) == 0) return TZ_America_Bogota;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Cambridge_Bay")) == 0) return TZ_America_Cambridge_Bay;
                else if (strcmp_P(c, PSTR("Campo_Grande")) == 0) return TZ_America_Campo_Grande;
                else return nullptr;
              } else {
                return TZ_America_Boise;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Cayenne"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Caracas")) == 0) return TZ_America_Caracas;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Cayman")) == 0) return TZ_America_Cayman;
                else if (strcmp_P(c, PSTR("Chicago")) == 0) return TZ_America_Chicago;
                else return nullptr;
              } else {
                return TZ_America_Cayenne;
              }
            } else {
              return TZ_America_Cancun;
            }
          } else {
            return TZ_America_Boa_Vista;
          }
        } else {
          return TZ_America_Aruba;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Goose_Bay"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Detroit"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Curacao"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Creston"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Costa_Rica")) == 0) return TZ_America_Costa_Rica;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Cuiaba")) == 0) return TZ_America_Cuiaba;
                else return nullptr;
              } else {
                return TZ_America_Creston;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Dawson"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Danmarkshavn")) == 0) return TZ_America_Danmarkshavn;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Dawson_Creek")) == 0) return TZ_America_Dawson_Creek;
                else if (strcmp_P(c, PSTR("Denver")) == 0) return TZ_America_Denver;
                else return nullptr;
              } else {
                return TZ_America_Dawson;
              }
            } else {
              return TZ_America_Curacao;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("El_Salvador"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Edmonton"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Dominica")) == 0) return TZ_America_Dominica;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Eirunepe")) == 0) return TZ_America_Eirunepe;
                else return nullptr;
              } else {
                return TZ_America_Edmonton;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Fortaleza"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Fort_Nelson")) == 0) return TZ_America_Fort_Nelson;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Glace_Bay")) == 0) return TZ_America_Glace_Bay;
                else if (strcmp_P(c, PSTR("Godthab")) == 0) return TZ_America_Godthab;
                else return nullptr;
              } else {
                return TZ_America_Fortaleza;
              }
            } else {
              return TZ_America_El_Salvador;
            }
          } else {
            return TZ_America_Detroit;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Hermosillo"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Guatemala"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Grenada"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Grand_Turk")) == 0) return TZ_America_Grand_Turk;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Guadeloupe")) == 0) return TZ_America_Guadeloupe;
                else return nullptr;
              } else {
                return TZ_America_Grenada;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Guyana"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Guayaquil")) == 0) return TZ_America_Guayaquil;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Halifax")) == 0) return TZ_America_Halifax;
                else if (strcmp_P(c, PSTR("Havana")) == 0) return TZ_America_Havana;
                else return nullptr;
              } else {
                return TZ_America_Guyana;
              }
            } else {
              return TZ_America_Guatemala;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Indiana/Tell_City"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Indiana/Knox"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Indiana/Indianapolis")) == 0) return TZ_America_Indiana_Indianapolis;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Indiana/Marengo")) == 0) return TZ_America_Indiana_Marengo;
                else if (strcmp_P(c, PSTR("Indiana/Petersburg")) == 0) return TZ_America_Indiana_Petersburg;
                else return nullptr;
              } else {
                return TZ_America_Indiana_Knox;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Indiana/Vincennes"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Indiana/Vevay")) == 0) return TZ_America_Indiana_Vevay;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Indiana/Winamac")) == 0) return TZ_America_Indiana_Winamac;
                else if (strcmp_P(c, PSTR("Inuvik")) == 0) return TZ_America_Inuvik;
                else return nullptr;
              } else {
                return TZ_America_Indiana_Vincennes;
              }
            } else {
              return TZ_America_Indiana_Tell_City;
            }
          } else {
            return TZ_America_Hermosillo;
          }
        } else {
          return TZ_America_Goose_Bay;
        }
      } else {
        return TZ_America_Chihuahua;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Pangnirtung"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Merida"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Lower_Princes"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Kentucky/Monticello"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Juneau"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Jamaica")) == 0) return TZ_America_Jamaica;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Kentucky/Louisville")) == 0) return TZ_America_Kentucky_Louisville;
                else return nullptr;
              } else {
                return TZ_America_Juneau;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("La_Paz"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Kralendijk")) == 0) return TZ_America_Kralendijk;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Lima")) == 0) return TZ_America_Lima;
                else if (strcmp_P(c, PSTR("Los_Angeles")) == 0) return TZ_America_Los_Angeles;
                else return nullptr;
              } else {
                return TZ_America_La_Paz;
              }
            } else {
              return TZ_America_Kentucky_Monticello;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Marigot"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Managua"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Maceio")) == 0) return TZ_America_Maceio;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Manaus")) == 0) return TZ_America_Manaus;
                else return nullptr;
              } else {
                return TZ_America_Managua;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Matamoros"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Martinique")) == 0) return TZ_America_Martinique;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Mazatlan")) == 0) return TZ_America_Mazatlan;
                else if (strcmp_P(c, PSTR("Menominee")) == 0) return TZ_America_Menominee;
                else return nullptr;
              } else {
                return TZ_America_Matamoros;
              }
            } else {
              return TZ_America_Marigot;
            }
          } else {
            return TZ_America_Lower_Princes;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Nassau"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Moncton"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Mexico_City"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Metlakatla")) == 0) return TZ_America_Metlakatla;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Miquelon")) == 0) return TZ_America_Miquelon;
                else return nullptr;
              } else {
                return TZ_America_Mexico_City;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Montevideo"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Monterrey")) == 0) return TZ_America_Monterrey;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Montreal")) == 0) return TZ_America_Montreal;
                else if (strcmp_P(c, PSTR("Montserrat")) == 0) return TZ_America_Montserrat;
                else return nullptr;
              } else {
                return TZ_America_Montevideo;
              }
            } else {
              return TZ_America_Moncton;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("North_Dakota/Beulah"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Nipigon"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("New_York")) == 0) return TZ_America_New_York;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Nome")) == 0) return TZ_America_Nome;
                else if (strcmp_P(c, PSTR("Noronha")) == 0) return TZ_America_Noronha;
                else return nullptr;
              } else {
                return TZ_America_Nipigon;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("North_Dakota/New_Salem"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("North_Dakota/Center")) == 0) return TZ_America_North_Dakota_Center;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Ojinaga")) == 0) return TZ_America_Ojinaga;
                else if (strcmp_P(c, PSTR("Panama")) == 0) return TZ_America_Panama;
                else return nullptr;
              } else {
                return TZ_America_North_Dakota_New_Salem;
              }
            } else {
              return TZ_America_North_Dakota_Beulah;
            }
          } else {
            return TZ_America_Nassau;
          }
        } else {
          return TZ_America_Merida;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Sitka"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Rankin_Inlet"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Port_of_Spain"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Phoenix"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Paramaribo")) == 0) return TZ_America_Paramaribo;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Port-au-Prince")) == 0) return TZ_America_PortmaumPrince;
                else return nullptr;
              } else {
                return TZ_America_Phoenix;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Puerto_Rico"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Porto_Velho")) == 0) return TZ_America_Porto_Velho;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Punta_Arenas")) == 0) return TZ_America_Punta_Arenas;
                else if (strcmp_P(c, PSTR("Rainy_River")) == 0) return TZ_America_Rainy_River;
                else return nullptr;
              } else {
                return TZ_America_Puerto_Rico;
              }
            } else {
              return TZ_America_Port_of_Spain;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Santarem"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Regina"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Recife")) == 0) return TZ_America_Recife;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Resolute")) == 0) return TZ_America_Resolute;
                else if (strcmp_P(c, PSTR("Rio_Branco")) == 0) return TZ_America_Rio_Branco;
                else return nullptr;
              } else {
                return TZ_America_Regina;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Santo_Domingo"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Santiago")) == 0) return TZ_America_Santiago;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Sao_Paulo")) == 0) return TZ_America_Sao_Paulo;
                else if (strcmp_P(c, PSTR("Scoresbysund")) == 0) return TZ_America_Scoresbysund;
                else return nullptr;
              } else {
                return TZ_America_Santo_Domingo;
              }
            } else {
              return TZ_America_Santarem;
            }
          } else {
            return TZ_America_Rankin_Inlet;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Thule"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("St_Lucia"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("St_Johns"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("St_Barthelemy")) == 0) return TZ_America_St_Barthelemy;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("St_Kitts")) == 0) return TZ_America_St_Kitts;
                else return nullptr;
              } else {
                return TZ_America_St_Johns;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("St_Vincent"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("St_Thomas")) == 0) return TZ_America_St_Thomas;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Swift_Current")) == 0) return TZ_America_Swift_Current;
                else if (strcmp_P(c, PSTR("Tegucigalpa")) == 0) return TZ_America_Tegucigalpa;
                else return nullptr;
              } else {
                return TZ_America_St_Vincent;
              }
            } else {
              return TZ_America_St_Lucia;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Vancouver"));
            if (r < 0) {
              r = strcmp_P(c, PSTR("Tijuana"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Thunder_Bay")) == 0) return TZ_America_Thunder_Bay;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Toronto")) == 0) return TZ_America_Toronto;
                else if (strcmp_P(c, PSTR("Tortola")) == 0) return TZ_America_Tortola;
                else return nullptr;
              } else {
                return TZ_America_Tijuana;
              }
            } else if (r > 0) {
              r = strcmp_P(c, PSTR("Winnipeg"));
              if (r < 0) {
                if (strcmp_P(c, PSTR("Whitehorse")) == 0) return TZ_America_Whitehorse;
                else return nullptr;
              } else if (r > 0) {
                if (strcmp_P(c, PSTR("Yakutat")) == 0) return TZ_America_Yakutat;
                else if (strcmp_P(c, PSTR("Yellowknife")) == 0) return TZ_America_Yellowknife;
                else return nullptr;
              } else {
                return TZ_America_Winnipeg;
              }
            } else {
              return TZ_America_Vancouver;
            }
          } else {
            return TZ_America_Thule;
          }
        } else {
          return TZ_America_Sitka;
        }
      } else {
        return TZ_America_Pangnirtung;
      }
    } else {
      return TZ_America_Iqaluit;
    }
  }
  else if (strcmp_P(a, PSTR("Antarctica")) == 0) {
    r = strcmp_P(c, PSTR("McMurdo"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("DumontDUrville"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Casey")) == 0) return TZ_Antarctica_Casey;
        else if (strcmp_P(c, PSTR("Davis")) == 0) return TZ_Antarctica_Davis;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("Macquarie")) == 0) return TZ_Antarctica_Macquarie;
        else if (strcmp_P(c, PSTR("Mawson")) == 0) return TZ_Antarctica_Mawson;
        else return nullptr;
      } else {
        return TZ_Antarctica_DumontDUrville;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Syowa"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Palmer")) == 0) return TZ_Antarctica_Palmer;
        else if (strcmp_P(c, PSTR("Rothera")) == 0) return TZ_Antarctica_Rothera;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("Troll")) == 0) return TZ_Antarctica_Troll;
        else if (strcmp_P(c, PSTR("Vostok")) == 0) return TZ_Antarctica_Vostok;
        else return nullptr;
      } else {
        return TZ_Antarctica_Syowa;
      }
    } else {
      return TZ_Antarctica_McMurdo;
    }
  }
  else if (strcmp_P(a, PSTR("Arctic")) == 0) {
    if (strcmp_P(c, PSTR("Longyearbyen")) == 0) return TZ_Arctic_Longyearbyen;
    else return nullptr;
  }
  else if (strcmp_P(a, PSTR("Asia")) == 0) {
    r = strcmp_P(c, PSTR("Krasnoyarsk"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Damascus"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Bahrain"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Aqtau"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Almaty"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Aden")) == 0) return TZ_Asia_Aden;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Amman")) == 0) return TZ_Asia_Amman;
              else if (strcmp_P(c, PSTR("Anadyr")) == 0) return TZ_Asia_Anadyr;
              else return nullptr;
            } else {
              return TZ_Asia_Almaty;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Ashgabat"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Aqtobe")) == 0) return TZ_Asia_Aqtobe;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Atyrau")) == 0) return TZ_Asia_Atyrau;
              else if (strcmp_P(c, PSTR("Baghdad")) == 0) return TZ_Asia_Baghdad;
              else return nullptr;
            } else {
              return TZ_Asia_Ashgabat;
            }
          } else {
            return TZ_Asia_Aqtau;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Bishkek"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Bangkok"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Baku")) == 0) return TZ_Asia_Baku;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Barnaul")) == 0) return TZ_Asia_Barnaul;
              else if (strcmp_P(c, PSTR("Beirut")) == 0) return TZ_Asia_Beirut;
              else return nullptr;
            } else {
              return TZ_Asia_Bangkok;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Chita"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Brunei")) == 0) return TZ_Asia_Brunei;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Choibalsan")) == 0) return TZ_Asia_Choibalsan;
              else if (strcmp_P(c, PSTR("Colombo")) == 0) return TZ_Asia_Colombo;
              else return nullptr;
            } else {
              return TZ_Asia_Chita;
            }
          } else {
            return TZ_Asia_Bishkek;
          }
        } else {
          return TZ_Asia_Bahrain;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Hovd"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Famagusta"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Dili"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Dhaka")) == 0) return TZ_Asia_Dhaka;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Dubai")) == 0) return TZ_Asia_Dubai;
              else if (strcmp_P(c, PSTR("Dushanbe")) == 0) return TZ_Asia_Dushanbe;
              else return nullptr;
            } else {
              return TZ_Asia_Dili;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Hebron"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Gaza")) == 0) return TZ_Asia_Gaza;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Ho_Chi_Minh")) == 0) return TZ_Asia_Ho_Chi_Minh;
              else if (strcmp_P(c, PSTR("Hong_Kong")) == 0) return TZ_Asia_Hong_Kong;
              else return nullptr;
            } else {
              return TZ_Asia_Hebron;
            }
          } else {
            return TZ_Asia_Famagusta;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Kabul"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Jakarta"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Irkutsk")) == 0) return TZ_Asia_Irkutsk;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Jayapura")) == 0) return TZ_Asia_Jayapura;
              else if (strcmp_P(c, PSTR("Jerusalem")) == 0) return TZ_Asia_Jerusalem;
              else return nullptr;
            } else {
              return TZ_Asia_Jakarta;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Kathmandu"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Kamchatka")) == 0) return TZ_Asia_Kamchatka;
              else if (strcmp_P(c, PSTR("Karachi")) == 0) return TZ_Asia_Karachi;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Khandyga")) == 0) return TZ_Asia_Khandyga;
              else if (strcmp_P(c, PSTR("Kolkata")) == 0) return TZ_Asia_Kolkata;
              else return nullptr;
            } else {
              return TZ_Asia_Kathmandu;
            }
          } else {
            return TZ_Asia_Kabul;
          }
        } else {
          return TZ_Asia_Hovd;
        }
      } else {
        return TZ_Asia_Damascus;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Samarkand"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Novokuznetsk"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Magadan"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Kuching"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Kuala_Lumpur")) == 0) return TZ_Asia_Kuala_Lumpur;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Kuwait")) == 0) return TZ_Asia_Kuwait;
              else if (strcmp_P(c, PSTR("Macau")) == 0) return TZ_Asia_Macau;
              else return nullptr;
            } else {
              return TZ_Asia_Kuching;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Manila"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Makassar")) == 0) return TZ_Asia_Makassar;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Muscat")) == 0) return TZ_Asia_Muscat;
              else if (strcmp_P(c, PSTR("Nicosia")) == 0) return TZ_Asia_Nicosia;
              else return nullptr;
            } else {
              return TZ_Asia_Manila;
            }
          } else {
            return TZ_Asia_Magadan;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Pontianak"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Omsk"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Novosibirsk")) == 0) return TZ_Asia_Novosibirsk;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Oral")) == 0) return TZ_Asia_Oral;
              else if (strcmp_P(c, PSTR("Phnom_Penh")) == 0) return TZ_Asia_Phnom_Penh;
              else return nullptr;
            } else {
              return TZ_Asia_Omsk;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Qyzylorda"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Pyongyang")) == 0) return TZ_Asia_Pyongyang;
              else if (strcmp_P(c, PSTR("Qatar")) == 0) return TZ_Asia_Qatar;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Riyadh")) == 0) return TZ_Asia_Riyadh;
              else if (strcmp_P(c, PSTR("Sakhalin")) == 0) return TZ_Asia_Sakhalin;
              else return nullptr;
            } else {
              return TZ_Asia_Qyzylorda;
            }
          } else {
            return TZ_Asia_Pontianak;
          }
        } else {
          return TZ_Asia_Novokuznetsk;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Tokyo"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Taipei"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Shanghai"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Seoul")) == 0) return TZ_Asia_Seoul;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Singapore")) == 0) return TZ_Asia_Singapore;
              else if (strcmp_P(c, PSTR("Srednekolymsk")) == 0) return TZ_Asia_Srednekolymsk;
              else return nullptr;
            } else {
              return TZ_Asia_Shanghai;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Tbilisi"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Tashkent")) == 0) return TZ_Asia_Tashkent;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Tehran")) == 0) return TZ_Asia_Tehran;
              else if (strcmp_P(c, PSTR("Thimphu")) == 0) return TZ_Asia_Thimphu;
              else return nullptr;
            } else {
              return TZ_Asia_Tbilisi;
            }
          } else {
            return TZ_Asia_Taipei;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Vientiane"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Ulaanbaatar"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Tomsk")) == 0) return TZ_Asia_Tomsk;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Urumqi")) == 0) return TZ_Asia_Urumqi;
              else if (strcmp_P(c, PSTR("Ust-Nera")) == 0) return TZ_Asia_UstmNera;
              else return nullptr;
            } else {
              return TZ_Asia_Ulaanbaatar;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Yangon"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Vladivostok")) == 0) return TZ_Asia_Vladivostok;
              else if (strcmp_P(c, PSTR("Yakutsk")) == 0) return TZ_Asia_Yakutsk;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Yekaterinburg")) == 0) return TZ_Asia_Yekaterinburg;
              else if (strcmp_P(c, PSTR("Yerevan")) == 0) return TZ_Asia_Yerevan;
              else return nullptr;
            } else {
              return TZ_Asia_Yangon;
            }
          } else {
            return TZ_Asia_Vientiane;
          }
        } else {
          return TZ_Asia_Tokyo;
        }
      } else {
        return TZ_Asia_Samarkand;
      }
    } else {
      return TZ_Asia_Krasnoyarsk;
    }
  }
  else if (strcmp_P(a, PSTR("Atlantic")) == 0) {
    r = strcmp_P(c, PSTR("Faroe"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Bermuda"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Azores")) == 0) return TZ_Atlantic_Azores;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("Canary")) == 0) return TZ_Atlantic_Canary;
        else if (strcmp_P(c, PSTR("Cape_Verde")) == 0) return TZ_Atlantic_Cape_Verde;
        else return nullptr;
      } else {
        return TZ_Atlantic_Bermuda;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("South_Georgia"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Madeira")) == 0) return TZ_Atlantic_Madeira;
        else if (strcmp_P(c, PSTR("Reykjavik")) == 0) return TZ_Atlantic_Reykjavik;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("St_Helena")) == 0) return TZ_Atlantic_St_Helena;
        else if (strcmp_P(c, PSTR("Stanley")) == 0) return TZ_Atlantic_Stanley;
        else return nullptr;
      } else {
        return TZ_Atlantic_South_Georgia;
      }
    } else {
      return TZ_Atlantic_Faroe;
    }
  }
  else if (strcmp_P(a, PSTR("Australia")) == 0) {
    r = strcmp_P(c, PSTR("Eucla"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Broken_Hill"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Adelaide")) == 0) return TZ_Australia_Adelaide;
        else if (strcmp_P(c, PSTR("Brisbane")) == 0) return TZ_Australia_Brisbane;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("Currie")) == 0) return TZ_Australia_Currie;
        else if (strcmp_P(c, PSTR("Darwin")) == 0) return TZ_Australia_Darwin;
        else return nullptr;
      } else {
        return TZ_Australia_Broken_Hill;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Lord_Howe"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Hobart")) == 0) return TZ_Australia_Hobart;
        else if (strcmp_P(c, PSTR("Lindeman")) == 0) return TZ_Australia_Lindeman;
        else return nullptr;
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Perth"));
        if (r < 0) {
          if (strcmp_P(c, PSTR("Melbourne")) == 0) return TZ_Australia_Melbourne;
          else return nullptr;
        } else if (r > 0) {
          if (strcmp_P(c, PSTR("Sydney")) == 0) return TZ_Australia_Sydney;
          else return nullptr;
        } else {
          return TZ_Australia_Perth;
        }
      } else {
        return TZ_Australia_Lord_Howe;
      }
    } else {
      return TZ_Australia_Eucla;
    }
  }
  else if (strcmp_P(a, PSTR("Europe")) == 0) {
    r = strcmp_P(c, PSTR("Mariehamn"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Gibraltar"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Bratislava"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Astrakhan"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Amsterdam")) == 0) return TZ_Europe_Amsterdam;
            else if (strcmp_P(c, PSTR("Andorra")) == 0) return TZ_Europe_Andorra;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Belgrade"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Athens")) == 0) return TZ_Europe_Athens;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Berlin")) == 0) return TZ_Europe_Berlin;
              else return nullptr;
            } else {
              return TZ_Europe_Belgrade;
            }
          } else {
            return TZ_Europe_Astrakhan;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Busingen"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Bucharest"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Brussels")) == 0) return TZ_Europe_Brussels;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Budapest")) == 0) return TZ_Europe_Budapest;
              else return nullptr;
            } else {
              return TZ_Europe_Bucharest;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Copenhagen"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Chisinau")) == 0) return TZ_Europe_Chisinau;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Dublin")) == 0) return TZ_Europe_Dublin;
              else return nullptr;
            } else {
              return TZ_Europe_Copenhagen;
            }
          } else {
            return TZ_Europe_Busingen;
          }
        } else {
          return TZ_Europe_Bratislava;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Kiev"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Isle_of_Man"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Guernsey")) == 0) return TZ_Europe_Guernsey;
            else if (strcmp_P(c, PSTR("Helsinki")) == 0) return TZ_Europe_Helsinki;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Jersey"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Istanbul")) == 0) return TZ_Europe_Istanbul;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Kaliningrad")) == 0) return TZ_Europe_Kaliningrad;
              else return nullptr;
            } else {
              return TZ_Europe_Jersey;
            }
          } else {
            return TZ_Europe_Isle_of_Man;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("London"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Lisbon"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Kirov")) == 0) return TZ_Europe_Kirov;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Ljubljana")) == 0) return TZ_Europe_Ljubljana;
              else return nullptr;
            } else {
              return TZ_Europe_Lisbon;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Madrid"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Luxembourg")) == 0) return TZ_Europe_Luxembourg;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Malta")) == 0) return TZ_Europe_Malta;
              else return nullptr;
            } else {
              return TZ_Europe_Madrid;
            }
          } else {
            return TZ_Europe_London;
          }
        } else {
          return TZ_Europe_Kiev;
        }
      } else {
        return TZ_Europe_Gibraltar;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Skopje"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Prague"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Moscow"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Minsk")) == 0) return TZ_Europe_Minsk;
            else if (strcmp_P(c, PSTR("Monaco")) == 0) return TZ_Europe_Monaco;
            else return nullptr;
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Paris"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Oslo")) == 0) return TZ_Europe_Oslo;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Podgorica")) == 0) return TZ_Europe_Podgorica;
              else return nullptr;
            } else {
              return TZ_Europe_Paris;
            }
          } else {
            return TZ_Europe_Moscow;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("San_Marino"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Rome"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Riga")) == 0) return TZ_Europe_Riga;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Samara")) == 0) return TZ_Europe_Samara;
              else return nullptr;
            } else {
              return TZ_Europe_Rome;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Saratov"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Sarajevo")) == 0) return TZ_Europe_Sarajevo;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Simferopol")) == 0) return TZ_Europe_Simferopol;
              else return nullptr;
            } else {
              return TZ_Europe_Saratov;
            }
          } else {
            return TZ_Europe_San_Marino;
          }
        } else {
          return TZ_Europe_Prague;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Vatican"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Tirane"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Stockholm"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Sofia")) == 0) return TZ_Europe_Sofia;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Tallinn")) == 0) return TZ_Europe_Tallinn;
              else return nullptr;
            } else {
              return TZ_Europe_Stockholm;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Uzhgorod"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Ulyanovsk")) == 0) return TZ_Europe_Ulyanovsk;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Vaduz")) == 0) return TZ_Europe_Vaduz;
              else return nullptr;
            } else {
              return TZ_Europe_Uzhgorod;
            }
          } else {
            return TZ_Europe_Tirane;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Warsaw"));
          if (r < 0) {
            r = strcmp_P(c, PSTR("Vilnius"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Vienna")) == 0) return TZ_Europe_Vienna;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Volgograd")) == 0) return TZ_Europe_Volgograd;
              else return nullptr;
            } else {
              return TZ_Europe_Vilnius;
            }
          } else if (r > 0) {
            r = strcmp_P(c, PSTR("Zaporozhye"));
            if (r < 0) {
              if (strcmp_P(c, PSTR("Zagreb")) == 0) return TZ_Europe_Zagreb;
              else return nullptr;
            } else if (r > 0) {
              if (strcmp_P(c, PSTR("Zurich")) == 0) return TZ_Europe_Zurich;
              else return nullptr;
            } else {
              return TZ_Europe_Zaporozhye;
            }
          } else {
            return TZ_Europe_Warsaw;
          }
        } else {
          return TZ_Europe_Vatican;
        }
      } else {
        return TZ_Europe_Skopje;
      }
    } else {
      return TZ_Europe_Mariehamn;
    }
  }
  else if (strcmp_P(a, PSTR("Indian")) == 0) {
    r = strcmp_P(c, PSTR("Kerguelen"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Christmas"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Antananarivo")) == 0) return TZ_Indian_Antananarivo;
        else if (strcmp_P(c, PSTR("Chagos")) == 0) return TZ_Indian_Chagos;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("Cocos")) == 0) return TZ_Indian_Cocos;
        else if (strcmp_P(c, PSTR("Comoro")) == 0) return TZ_Indian_Comoro;
        else return nullptr;
      } else {
        return TZ_Indian_Christmas;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Mauritius"));
      if (r < 0) {
        if (strcmp_P(c, PSTR("Mahe")) == 0) return TZ_Indian_Mahe;
        else if (strcmp_P(c, PSTR("Maldives")) == 0) return TZ_Indian_Maldives;
        else return nullptr;
      } else if (r > 0) {
        if (strcmp_P(c, PSTR("Mayotte")) == 0) return TZ_Indian_Mayotte;
        else if (strcmp_P(c, PSTR("Reunion")) == 0) return TZ_Indian_Reunion;
        else return nullptr;
      } else {
        return TZ_Indian_Mauritius;
      }
    } else {
      return TZ_Indian_Kerguelen;
    }
  }
  else if (strcmp_P(a, PSTR("Pacific")) == 0) {
    r = strcmp_P(c, PSTR("Kwajalein"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("Fakaofo"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Chatham"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Auckland"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Apia")) == 0) return TZ_Pacific_Apia;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Bougainville")) == 0) return TZ_Pacific_Bougainville;
            else return nullptr;
          } else {
            return TZ_Pacific_Auckland;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Easter"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Chuuk")) == 0) return TZ_Pacific_Chuuk;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Efate")) == 0) return TZ_Pacific_Efate;
            else if (strcmp_P(c, PSTR("Enderbury")) == 0) return TZ_Pacific_Enderbury;
            else return nullptr;
          } else {
            return TZ_Pacific_Easter;
          }
        } else {
          return TZ_Pacific_Chatham;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Guadalcanal"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Funafuti"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Fiji")) == 0) return TZ_Pacific_Fiji;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Galapagos")) == 0) return TZ_Pacific_Galapagos;
            else if (strcmp_P(c, PSTR("Gambier")) == 0) return TZ_Pacific_Gambier;
            else return nullptr;
          } else {
            return TZ_Pacific_Funafuti;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Honolulu"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Guam")) == 0) return TZ_Pacific_Guam;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Kiritimati")) == 0) return TZ_Pacific_Kiritimati;
            else if (strcmp_P(c, PSTR("Kosrae")) == 0) return TZ_Pacific_Kosrae;
            else return nullptr;
          } else {
            return TZ_Pacific_Honolulu;
          }
        } else {
          return TZ_Pacific_Guadalcanal;
        }
      } else {
        return TZ_Pacific_Fakaofo;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("Pitcairn"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("Niue"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Marquesas"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Majuro")) == 0) return TZ_Pacific_Majuro;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Midway")) == 0) return TZ_Pacific_Midway;
            else if (strcmp_P(c, PSTR("Nauru")) == 0) return TZ_Pacific_Nauru;
            else return nullptr;
          } else {
            return TZ_Pacific_Marquesas;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Noumea"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Norfolk")) == 0) return TZ_Pacific_Norfolk;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Pago_Pago")) == 0) return TZ_Pacific_Pago_Pago;
            else if (strcmp_P(c, PSTR("Palau")) == 0) return TZ_Pacific_Palau;
            else return nullptr;
          } else {
            return TZ_Pacific_Noumea;
          }
        } else {
          return TZ_Pacific_Niue;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Tahiti"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("Port_Moresby"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Pohnpei")) == 0) return TZ_Pacific_Pohnpei;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Rarotonga")) == 0) return TZ_Pacific_Rarotonga;
            else if (strcmp_P(c, PSTR("Saipan")) == 0) return TZ_Pacific_Saipan;
            else return nullptr;
          } else {
            return TZ_Pacific_Port_Moresby;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("Tongatapu"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("Tarawa")) == 0) return TZ_Pacific_Tarawa;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Wake")) == 0) return TZ_Pacific_Wake;
            else if (strcmp_P(c, PSTR("Wallis")) == 0) return TZ_Pacific_Wallis;
            else return nullptr;
          } else {
            return TZ_Pacific_Tongatapu;
          }
        } else {
          return TZ_Pacific_Tahiti;
        }
      } else {
        return TZ_Pacific_Pitcairn;
      }
    } else {
      return TZ_Pacific_Kwajalein;
    }
  }
  else if (strcmp_P(a, PSTR("Etc")) == 0) {
    r = strcmp_P(c, PSTR("GMT-11"));
    if (r < 0) {
      r = strcmp_P(c, PSTR("GMT+4"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("GMT+10"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("GMT+0"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT")) == 0) return TZ_Etc_GMT;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT+1")) == 0) return TZ_Etc_GMTp1;
            else return nullptr;
          } else {
            return TZ_Etc_GMTp0;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("GMT+12"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT+11")) == 0) return TZ_Etc_GMTp11;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT+2")) == 0) return TZ_Etc_GMTp2;
            else if (strcmp_P(c, PSTR("GMT+3")) == 0) return TZ_Etc_GMTp3;
            else return nullptr;
          } else {
            return TZ_Etc_GMTp12;
          }
        } else {
          return TZ_Etc_GMTp10;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("GMT+8"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("GMT+6"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT+5")) == 0) return TZ_Etc_GMTp5;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT+7")) == 0) return TZ_Etc_GMTp7;
            else return nullptr;
          } else {
            return TZ_Etc_GMTp6;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("GMT-0"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT+9")) == 0) return TZ_Etc_GMTp9;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT-1")) == 0) return TZ_Etc_GMTm1;
            else if (strcmp_P(c, PSTR("GMT-10")) == 0) return TZ_Etc_GMTm10;
            else return nullptr;
          } else {
            return TZ_Etc_GMTm0;
          }
        } else {
          return TZ_Etc_GMTp8;
        }
      } else {
        return TZ_Etc_GMTp4;
      }
    } else if (r > 0) {
      r = strcmp_P(c, PSTR("GMT-7"));
      if (r < 0) {
        r = strcmp_P(c, PSTR("GMT-2"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("GMT-13"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT-12")) == 0) return TZ_Etc_GMTm12;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT-14")) == 0) return TZ_Etc_GMTm14;
            else return nullptr;
          } else {
            return TZ_Etc_GMTm13;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("GMT-4"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT-3")) == 0) return TZ_Etc_GMTm3;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT-5")) == 0) return TZ_Etc_GMTm5;
            else if (strcmp_P(c, PSTR("GMT-6")) == 0) return TZ_Etc_GMTm6;
            else return nullptr;
          } else {
            return TZ_Etc_GMTm4;
          }
        } else {
          return TZ_Etc_GMTm2;
        }
      } else if (r > 0) {
        r = strcmp_P(c, PSTR("Greenwich"));
        if (r < 0) {
          r = strcmp_P(c, PSTR("GMT-9"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("GMT-8")) == 0) return TZ_Etc_GMTm8;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("GMT0")) == 0) return TZ_Etc_GMT0;
            else return nullptr;
          } else {
            return TZ_Etc_GMTm9;
          }
        } else if (r > 0) {
          r = strcmp_P(c, PSTR("UTC"));
          if (r < 0) {
            if (strcmp_P(c, PSTR("UCT")) == 0) return TZ_Etc_UCT;
            else return nullptr;
          } else if (r > 0) {
            if (strcmp_P(c, PSTR("Universal")) == 0) return TZ_Etc_Universal;
            else if (strcmp_P(c, PSTR("Zulu")) == 0) return TZ_Etc_Zulu;
            else return nullptr;
          } else {
            return TZ_Etc_UTC;
          }
        } else {
          return TZ_Etc_Greenwich;
        }
      } else {
        return TZ_Etc_GMTm7;
      }
    } else {
      return TZ_Etc_GMTm11;
    }
  }
  return TZ_Etc_UTC;
}
const size_t TZDB::area_maxlength = 11;
const size_t TZDB::city_maxlength = 23;
